# fly.toml file generated for australialottov1 on 2022-12-03T02:16:03-03:00

app = "australialottov1"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  URL_MONDAY = "https://api.lotterywest.wa.gov.au/api/v1/games/5128/results-csv"
  URL_OZZ = "https://api.lotterywest.wa.gov.au/api/v1/games/5130/results-csv"
  URL_SFLIFE = "https://api.lotterywest.wa.gov.au/api/v1/games/5237/results-csv"
  URL_WEDNESDAY = "https://api.lotterywest.wa.gov.au/api/v1/games/5129/results-csv"
  URL_POWER = "https://api.lotterywest.wa.gov.au/api/v1/games/5132/results-csv"
  URL_SATURDAY = "https://api.lotterywest.wa.gov.au/api/v1/games/5127/results-csv"
  URL_MONGO = "mongodb+srv://deploy:uploaddeploy@australialotto.qrsru.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

  
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
